### ISSUE TITLE
remote-dir dont work

### ISSUE THREAD

**Issue by poznet** [bohoffi/ngx-deploy-ftp#11]
Angular CLI: 13.3.4
Node: 14.16.1
Package Manager: npm 6.14.12
OS: win32 x64

in my angular.json
```
 "options": {
            "host": "",
            "username": "",
            "password": "",
            "remote-dir": "public_html/test1",
            "tls" : false
          }
```
public_html is a dir not a symbolic  link
Everything works  but  files are always pushed to the default connection location (remote-dir doesn't work)

**Comment by bohoffi** [comment]
Hi @poznet 
Have you tried using the remote-dir parameter passed directly to the CLI call before?
When used in the angular.json you have to declare it as `"remoteDir"`.

**Comment by poznet** [comment]
@bohoffi  
You're right  :) I have "remote-dir"   instead of  "remoteDir"  in angular.json :) 
Stupid mistake
Thx  for  help
