### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by rig8f** [bohoffi/ngx-deploy-ftp#12]
By looking at package.json it seems that Angular 14 is not covered. Is it supported? Should dependency versions be updated to include Angular latest versions?

```jsonc
  // ...
  "devDependencies": {
    "@angular-devkit/architect": ">= 0.900 < 0.1400",
    "@angular-devkit/core": "^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0",
    "@angular-devkit/schematics": "^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0",
    // ...
  },
  "peerDependencies": {
    "@angular-devkit/architect": ">= 0.900 < 0.1400",
    "@angular-devkit/core": "^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0",
    "@angular-devkit/schematics": "^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0"
  },
  // ...
  ```

Right now, including this package into an Angular 14 project causes npm to downgrade all dependency versions.

Thank you!

**Comment by bohoffi** [comment]
Hi @rig8f,

this project started as an experiment and isn't in a broader focus by the OSS community.
If you need a version fully compatible to Angular 14 and 15 the required steps can be done but I cannot give a detailed ETA right now.
On the other hand feel free to publish a PR yourself.

**Comment by rig8f** [comment]
Hi @bohoffi,
what details should be checked, apart from bumping dependencies?
I may have a look at it, but I'm not sure how to check full compatibility, or if anything else has to be modified in order to work with latest Angular versions.
Thank you!

**Comment by bohoffi** [comment]
The core FTP related code isn't related to Angular so this code should be fine.

As you can see from the `peerDependencies` it should be enough to update the `@angular`-dependencies.

**Comment by bohoffi** [comment]
@rig8f you may have noticed that I found the time updating the Angular dependencies - so feel free to give version `2.0.0` a go
