### ISSUE TITLE
Angular 12 / 13 Support

### ISSUE THREAD

**Issue by JohannesHoppe** [bohoffi/ngx-deploy-ftp#5]
The following error occurs on a fresh Angular 13 project:

```
ng add ngx-deploy-ftp

ℹ Using package manager: npm
⚠ Unable to find compatible package.  Using 'latest' tag.
⚠ Package has unmet peer dependencies. Adding the package may not succeed.

The package ngx-deploy-ftp@1.0.0-next.1 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
See "/private/var/folders/65/0k8dncr10pj8lqmh192hjqgc0000gn/T/ng-5Dkb7c/angular-errors.log" for further details.
```

This is well-know breaking change of Angular 12, please see this commit:

https://github.com/angular-schule/ngx-deploy-starter/commit/55b7c98dd7e8094ec68db232aa1abd4a2b4650a8

We also added support for Angular 13 to the `npx-deploy-starter` demo here:

https://github.com/angular-schule/ngx-deploy-starter/commit/337e3c6d9edc22746528f2b2e9a33da7dbabd3d3

Greetings,
Johannes

**Comment by twiedow** [comment]
It would be great if there will be a new release with Angular 12 / 13 support.

**Comment by bohoffi** [comment]
@JohannesHoppe @twiedow I'll make the required changes as soon as I find the time to.

PRs welcome

**Comment by bohoffi** [comment]
@JohannesHoppe @twiedow support updated via `1.0.0-next.2` which was published to npm just now

**Comment by JohannesHoppe** [comment]
Such a version will be ignored by yarn, and it will still use the old version. Please bump to `1.0.0`. See https://github.com/angular-schule/angular-cli-ghpages/issues/140

**Comment by bohoffi** [comment]
@JohannesHoppe I'm sorry - I didn't know about such an issue with yarn. `1.0.0` is up now
