### ISSUE TITLE
Timeout (control socket) while running engine

### ISSUE THREAD

**Issue by cocomo** [bohoffi/ngx-deploy-ftp#7]
Please: I get a timeout error (control socket) with the --verbose option enabled. How do I find out what precisely timed out?

Input:
`ng deploy --host 'my-host.url' --port 23 --tls --username 'myusername' --password 'mypassword' --remote-dir '/path/to/my/folder' --clean-remote --verbose --no-build --dry-run`

Output:
```
Your global Angular CLI version (13.1.2) is greater than your local version (11.2.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
📦 Skipping build
🔍 Verifying passed options...
✔️ Verified passed options
As --dry-Run was used nothing will get changed on the remote.
🌐 Connecting to remote...
Connected to 12.34.56.78:23 (No encryption)
< SSH-2.0-mod_sftp

7ϛ�#�|WT�S��ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,rsa1024-sha1,ext-info-s=ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss_aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,cast128-cbc,3des-ctr,3des-cbc_aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,cast128-cbc,3des-ctr,3des-cbc[hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,umac-64@openssh.com,umac-128@openssh.com[hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,umac-64@openssh.com,umac-128@openssh.comnonenoneh�׮i
❌ An error occurred!
❌ An error occurred when trying to deploy:
Timeout (control socket)
```

Thank You :)

**Comment by bohoffi** [comment]
Hey @cocomo thanks for reporting. I'll have a look into this during the next few days. From what I think having a quick look and comparing your log outputs with the code the timeout happens between connecting to the host and switching the hosts working dir as you've provided the remote dir parameter and the log output that the dir will be changed never reached your terminal.

In the meantime: Have you checked that the host you're trying to connect to actually supports the actions you wanna do?

**Comment by cocomo** [comment]
Thank You @bohoffi for the quick reply :-) I think the server should support my options, i copied most of the settings from Filezillas Site Manager, like: host, port, protocol (sftp), username.. I also played with some of the parameters, i.e. change the port to 22, got rid of tls along with changing port to 20 and 21.. I just wish i could get more information about what's actually causing the timeout error. The remote directory is accessible by Filezilla from my ftp user ..

**Comment by bohoffi** [comment]
I have a request @cocomo 
As I can't reproduce the exact same error myself because I won't ask for your configuration parameters:

What IDE are you using? If it's VS Code could you try to debug the execution of the deploy process? The location for the breakpoint of interest would be inside `node_modules\ngx-deploy-ftp` - I'd like to be more precise about the further sub path but I don't have my computer around right now - you'd have to look for the log statement
```ts
context.logger.error('❌ An error occured when trying to deploy:');
```
Set a breakpoint on the subsequent statement which logs the errors message (`e.message`) and you'd be able to obtain more details from the error object itself.

I'm really sorry for the inconvenience of handing the errors message only to the user. I'll update the error logging to print out more - or even better all - information on Wednesday.

**Comment by bohoffi** [comment]
Hey @cocomo I just released `v1.1.0` to npm which includes increased log output in case of an error. I do hope that this can help you with your issue.

**Comment by cocomo** [comment]
Thank You very much @bohoffi for the quick reply and the new release :-) Unfortunately I am at the moment quite busy with other duties, but I will hopefully get back to testing within the next 2 weeks.

**Comment by cocomo** [comment]
Please @bohoffi : What would I look out for in the run and debug window of VS Code? The error object listed there does not provide new insights to me, the only thing that makes me wonder is that the socket is called `<anonymous>`. Does that state the ftp process cannot connect to the server? Should i send any particular output from the vscode debugging panels?

The upgraded ngx-deploy-ftp module provides also no new insights to me, here is my current output:

```
ng deploy --host 'ngcobalt###.manitu.net' --port 23 --username '###########' --password '###########' --remote-dir '/web/path/live' --clean-remote --verbose --no-build --dry-run
Debugger listening on ws://127.0.0.1:51878/c88ad17c-2a46-423b-bdae-bc0f23f8d1ac
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Your global Angular CLI version (13.1.2) is greater than your local version (11.2.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
📦 Skipping build
🔍 Verifying passed options...
✔️ Verified passed options
As --dry-Run was used nothing will get changed on the remote.
🌐 Connecting to remote...
Connected to 89.238.73.112:23 (No encryption)
< SSH-2.0-mod_sftp

�)͕���0�Kfn�K�ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,rsa1024-sha1,ext-info-s=ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss_aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,cast128-cbc,3des-ctr,3des-cbc_aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,cast128-cbc,3des-ctr,3des-cbc[hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,umac-64@openssh.com,umac-128@openssh.com[hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,umac-64@openssh.com,umac-128@openssh.comnonenone9��;
❌ An error occurred when trying to deploy:


```

**Comment by cocomo** [comment]
I finally got it deploying 🚀  Probably i did not provide my ssh-key in the desired process to the web hosting service? After successfully connecting to the server via sftp and ssh i changed the port in ng-deploy-ftp to 21 and things started running. I wish i could have done it via SFTP, but as far as i understand it FTPS seems to be a viable solution to easily deploy code for a non-profit charity project. Thank You @bohoffi for sharing and maintaining this awesome piece of software :-)

**Comment by bohoffi** [comment]
Hey @cocomo I'm glad to hear that you got it running in the end :)
Sadly this lib supports FTP only which is statet in the README but maybe I should point that out more clearly. I'll have a look on the error logging one more time as it seems that there was no output at all in your last terminal snippet.

**Comment by cocomo** [comment]
I'll be glad to try, just let me know when the new version comes up (still might take some time due to other duties :) @bohoffi
